
class WilayahOfflineService {
  static const Map<String, Map<String, Map<String, List<String>>>> _wilayahMap = {
    'Nusa Tenggara Barat (NTB)': {
      'Kab. Lombok Utara': {
        'Pemenang': [
          'Desa Pemenang Barat',
          'Desa Pemenang Timur',
          'Desa Malaka',
          'Desa Gili Indah (Gili Trawangan, Meno, Air)',
        ],
        'Tanjung': [
          'Desa Tanjung',
          'Desa Sokong',
          'Desa Medana',
          'Desa Jenggala',
          'Desa Teniga',
        ],
        'Gangga': [
          'Desa Gondang',
          'Desa Bentek',
          'Desa Genggelang',
          'Desa Rempek',
          'Desa Rempek Darat',
          'Desa Sambik Bangkol',
        ],
        'Bayan': [
          'Desa Anyar',
          'Desa Bayan',
          'Desa Karang Bajo',
          'Desa Loloan',
          'Desa Sukadana',
          'Desa Senaru',
          'Desa Batu Keliang',
          'Desa Sambik Elen',
          'Desa Akar-Akar',
        ],
        'Kayangan': [
          'Desa Kayangan',
          'Desa Dangiang',
          'Desa Gumantar',
          'Desa Sesait',
          'Desa Pendua',
          'Desa Selengen',
          'Desa Santong',
          'Desa Santong Mulia',
        ],
      },
      'Kab. Lombok Barat': {
        'Gerung': [
          'Gerung Utara',
          'Gerung Selatan',
          'Dasan Tapen',
          'Banyu Urip',
          'Babussalam',
          'Beleke',
          'Kebun Ayu',
          'Mesanggok',
          'Suka Makmur',
          'Taman Ayu',
        ],
        'Kediri': [
          'Kediri',
          'Kediri Selatan',
          'Rumak',
          'Montong Are',
          'Gelogor',
          'Jatisela',
          'Lelede',
          'Ombe Desa',
          'Parianum',
        ],
        'Narmada': [
          'Narmada',
          'Lembuak',
          'Nyurbaya',
          'Suranadi',
          'Badrain',
          'Batu Kuta',
          'Cramat',
          'Mekarsari',
          'Peresak',
          'Sembung',
          'Tanak Beak',
        ],
        'Batu Layar': [
          'Batu Layar',
          'Senggigi',
          'Meninting',
          'Sandik',
          'Batu Layar Barat',
          'Bengkaung',
          'Lembah Sari',
          'Pusuk Lestari',
        ],
        'Gunungsari': [
          'Gunungsari',
          'Midang',
          'Mambalan',
          'Tamansari',
          'Bukittinggi',
          'Dopang',
          'Jatisela',
          'Kekeri',
          'Kekait',
          'Penimbung',
          'Sesela',
        ],
        'Lingsar': [
          'Lingsar',
          'Batu Kumbung',
          'Peteluan Indah',
          'Sigra Indah',
          'Batu Mekar',
          'Duman',
          'Gontoran',
          'Karang Bayan',
          'Langko',
        ],
        'Labuapi': [
          'Labuapi',
          'Bengkel',
          'Bajur',
          'Kuranji',
          'Merembu',
          'Perampuan',
          'Terong Tawah',
          'Telagawaru',
        ],
        'Lembar': [
          'Lembar',
          'Lembar Selatan',
          'Mareje',
          'Eyat Mayang',
          'Jatimulya',
          'Labuan Tereng',
          'Sekotong Timur',
        ],
        'Sekotong': [
          'Sekotong Barat',
          'Sekotong Tengah',
          'Pelangan',
          'Buwun Mas',
          'Cendik Manik',
          'Batu Putih',
          'Gili Gede Indah',
        ],
        'Kuripan': [
          'Kuripan',
          'Kuripan Utara',
          'Kuripan Selatan',
          'Jajang',
          'Giri Sasak',
        ],
      },
      'Kota Mataram': {
        'Mataram': [
          'Mataram Timur',
          'Pagejahan',
          'Pejanggik',
          'Punia',
          'Pagutan',
          'Pagutan Barat',
          'Pagutan Timur',
        ],
        'Ampenan': [
          'Ampenan Selatan',
          'Ampenan Utara',
          'Bintaro',
          'Daya Peken',
          'Ampenan Tengah',
          'Banjar',
          'Boya',
          'Dayan Peken',
          'Pejeruk',
          'Taman Sari',
        ],
        'Cakranegara': [
          'Cakranegara Barat',
          'Cakranegara Timur',
          'Cakra Selatan',
          'Mayura',
          'Cakranegara Utara',
          'Cilinaya',
          'Karang Taliwang',
          'Sapta Marga',
          'Sayang-Sayang',
        ],
        'Sekarbela': [
          'Jembangan',
          'Karang Pule',
          'Kekalik Jaya',
          'Tanjung Karang',
          'Tanjung Karang Permai',
        ],
        'Selaparang': [
          'Dasan Agung',
          'Dasan Agung Baru',
          'Monjok',
          'Monjok Barat',
          'Monjok Timur',
          'Rembiga',
          'Sayang-Sayang',
        ],
        'Sandubaya': [
          'Bertais',
          'Abian Tubuh Baru',
          'Dasan Cerme',
          'Mandalika',
          'Selagalas',
          'Turida',
        ],
      },
      'Kab. Lombok Tengah': {
        'Praya': [
          'Praya',
          'Semayan',
          'Tiuh',
          'Renteng',
          'Gerunung',
          'Gonjak',
          'Leneng',
          'Panji Makmur',
          'Perapen',
          'Prapen',
        ],
        'Pujut': [
          'Sengkol',
          'Kuta (Mandalika)',
          'Rembitan',
          'Tanjung Ringgit',
          'Prabu',
          'Tumpak',
          'Sukadana',
          'Ketara',
          'Mertak',
          'Pengengat',
        ],
        'Jonggat': [
          'Puyung',
          'Bunken',
          'Sukarara',
          'Nambung',
          'Barejulat',
          'Jelantik',
          'Labulia',
          'Ubung',
        ],
        'Batukliang': [
          'Mantang',
          'Aik Darek',
          'Beber',
          'Barabali',
          'Bujak',
          'Tampak Siring',
        ],
        'Batukliang Utara': [
          'Teratak',
          'Lantan',
          'Aik Berik',
          'Karang Sidemen',
          'Mas-Mas',
          'Setiling',
        ],
        'Janapria': [
          'Janapria',
          'Durian',
          'Jango',
          'Kerembong',
          'Langko',
          'Loang Maka',
          'Pendem',
        ],
        'Kopang': [
          'Kopang Rembiga',
          'Bebesa',
          'Bebuak',
          'Dasan Baru',
          'Garung',
          'Mangkung',
        ],
        'Praya Barat': [
          'Penujak',
          'Batin',
          'Bonder',
          'Kateng',
          'Mangkung',
          'Mekar Sari',
        ],
        'Praya Barat Daya': [
          'Praya Barat Daya',
          'Batu Jangkih',
          'Darek',
          'Kabel',
          'Montong Ajan',
        ],
        'Praya Timur': [
          'Mujur',
          'Beleka',
          'Ganti',
          'Landah',
          'Marong',
          'Sengkerang',
        ],
        'Praya Tengah': [
          'Batunyala',
          'Biju',
          'Dakung',
          'Gerantung',
          'Jantuk',
          'Lajut',
          'Pejanggik',
        ],
        'Pringgarata': [
          'Pringgarata',
          'Arjangka',
          'Bagu',
          'Bilebante',
          'Menemeng',
          'Purna Barat',
        ],
      },
      'Kab. Lombok Timur': {
        'Selong': [
          'Selong',
          'Keliwates',
          'Pancor',
          'Rumbuk',
          'Majidi',
          'Sandubaya',
          'Sekarteja',
        ],
        'Labuhan Haji': [
          'Labuhan Haji',
          'Korleko',
          'Tanjung',
          'Tiram',
          'Penedagandeng',
          'Ijobalit',
        ],
        'Aikmel': ['Aikmel', 'Kalijaga', 'Prambanan', 'Kalijaga Selatan', 'Toya'],
        'Masbagik': [
          'Masbagik Utara',
          'Masbagik Selatan',
          'Paok Motong',
          'Kesik',
          'Danger',
          'Lendang Nangka',
        ],
        'Keruak': [
          'Keruak',
          'Batu Putik',
          'Dane Rase',
          'Ketapang Raya',
          'Selebundar',
          'Tanjung Luar',
        ],
        'Jerowaru': [
          'Jerowaru',
          'Ekas Buana',
          'Pemongkong',
          'Sekaroh',
          'Sepit',
          'Sukaraja',
          'Seriwe',
        ],
        'Pringgabaya': [
          'Pringgabaya',
          'Bagik Papan',
          'Batuyang',
          'Labuhan Lombok',
          'Pohgading',
          'Pohgading Timur',
        ],
        'Sambelia': [
          'Sambelia',
          'Belanting',
          'Labuhan Pandan',
          'Sugian',
          'Senaru',
        ],
        'Suralaga': [
          'Suralaga',
          'Anjani',
          'Bagik Payung',
          'Dames Damai',
          'Gapuk',
          'Tebaban',
        ],
        'Terara': [
          'Terara',
          'Embas-Embas',
          'Kalianyar',
          'Lando',
          'Leming',
          'Pandan Duri',
          'Santong',
        ],
        'Sikur': [
          'Sikur',
          'Gelora',
          'Montong Baan',
          'Semaya',
          'Tetebatu',
          'Tetebatu Selatan',
        ],
        'Montong Gading': [
          'Montong Betok',
          'Kilang',
          'Lendang Nangka Utara',
          'Perian',
        ],
        'Wanasaba': [
          'Wanasaba',
          'Bandok',
          'Beriri Jarak',
          'Jineng',
          'Karang Baru',
          'TLD',
        ],
        'Sembalun': [
          'Sembalun Bumbung',
          'Sembalun Lawang',
          'Sajang',
          'Timbanuh',
        ],
      },
      'Kab. Sumbawa': {
        'Sumbawa': ['Brang Biji', 'Brang Bara', 'Bugis', 'Lempeh', 'Seketeng', 'Uma Sima'],
        'Labuhan Badas': ['Labuhan Sumbawa', 'Sebotok', 'Badas', 'Karang Dima'],
        'Moyo Utara': ['Moyo', 'Baru', 'Pungkit', 'Songkar'],
        'Moyo Hilir': ['Moyo Hilir', 'Berare', 'Kakiang', 'Olat Rawa'],
        'Unter Ives': ['Unter Ives', 'Nijang', 'Pelat'],
      },
      'Kab. Sumbawa Barat': {
        'Taliwang': ['Kuang', 'Menala', 'Taliwang', 'Sampir', 'Telaga Linar', 'Arab Kenangan'],
        'Jereweh': ['Beru', 'Belo', 'Dasan'],
        'Maluk': ['Maluk', 'Pasir Putih', 'Bukit Hashim'],
        'Sekongkang': ['Sekongkang Bawah', 'Sekongkang Atas', 'Tatar', 'Tongo'],
      },
      'Kab. Dompu': {
        'Dompu': ['Bada', 'Bali', 'Karijawa', 'Dorotangga', 'Monta Baru'],
        'Woja': ['Simpasai', 'Kandai Dua', 'Monta'],
        'Pekat': ['Calabai', 'Pekat', 'Nangamiro'],
      },
      'Kab. Bima': {
        'Woha': ['Raba', 'Penapali', 'Tente', 'Donggo', 'Naru'],
        'Sape': ['Sape', 'Bugis', 'Rasabou', 'Naru'],
        'Bolo': ['Rato', 'Rasabou', 'Leu'],
      },
      'Kota Bima': {
        'Rasanae Barat': ['Dara', 'Pane', 'Paruga', 'Nae'],
        'Rasanae Timur': ['Kodo', 'Kumbe', 'Nungga', 'Obo'],
        'Asakota': ['Jatibaru', 'Melayu', 'Kolo'],
      },
    },
    'Bali': {
      'Kota Denpasar': {
        'Denpasar Selatan': [
          'Sanur',
          'Sanur Kauh',
          'Sanur Kaja',
          'Sidakarya',
          'Renon',
          'Panjer',
          'Pemogan',
          'Pedungan',
          'Serangan',
        ],
        'Denpasar Barat': [
          'Pemecutan',
          'Pemecutan Kelod',
          'Dauh Puri',
          'Dauh Puri Kangin',
          'Dauh Puri Kauh',
          'Dauh Puri Kelod',
          'Padangsambian',
          'Padangsambian Kaja',
          'Padangsambian Kelod',
        ],
        'Denpasar Utara': [
          'Peguyangan',
          'Peguyangan Kaja',
          'Peguyangan Kangin',
          'Ubung',
          'Ubung Kaja',
          'Tonja',
          'Pemecutan Kaja',
        ],
        'Denpasar Timur': [
          'Kesiman',
          'Kesiman Kerti',
          'Kesiman Petilan',
          'Sumerta',
          'Sumerta Kaja',
          'Sumerta Kauh',
          'Sumerta Kelod',
          'Dangin Puri',
          'Dangin Puri Kaja',
          'Dangin Puri Kangin',
          'Dangin Puri Kauh',
          'Penatih',
          'Penatih Dangin Puri',
        ],
      },
      'Kab. Badung': {
        'Kuta': ['Kuta', 'Legian', 'Seminyak', 'Tuban', 'Kedonganan'],
        'Kuta Selatan': ['Jimbaran', 'Nusa Dua (Benoa)', 'Pecatu', 'Ungasan', 'Kutuh'],
        'Kuta Utara': ['Canggu', 'Kerobokan', 'Kerobokan Kelod', 'Kerobokan Kaja', 'Tibubeneng', 'Dalung'],
        'Mengwi': ['Mengwi', 'Sempidi', 'Kapal', 'Lukluk', 'Abianbase', 'Penarungan', 'Buduk', 'Sembung', 'Sobangan'],
        'Abiansemal': ['Abiansemal', 'Blahkiuh', 'Mambal', 'Bongkasa', 'Sibang Kaja', 'Sibang Gede'],
        'Petang': ['Petang', 'Carangsari', 'Sulangai', 'Belok Sidan'],
      },
      'Kab. Gianyar': {
        'Ubud': ['Ubud', 'Peliatan', 'Petulu', 'Sayan', 'Singakerta', 'Kedewatan', 'Lodtunduh'],
        'Gianyar': ['Gianyar', 'Abianbase', 'Beng', 'Bitera', 'Samplangan', 'Tegal Tugu'],
        'Sukawati': ['Sukawati', 'Batubulan', 'Batubulan Kangin', 'Celuk', 'Singapadu', 'Guwang'],
        'Blahbatuh': ['Blahbatuh', 'Bedulu', 'Buruan', 'Keramas', 'Saba'],
        'Tampaksiring': ['Tampaksiring', 'Manukaya', 'Pejeng'],
        'Tegallalang': ['Tegallalang', 'Taro', 'Sebatu', 'Pujung'],
        'Payangan': ['Payangan', 'Melinggih', 'Buahan'],
      },
      'Kab. Buleleng': {
        'Buleleng (Singaraja)': [
          'Singaraja',
          'Banyuasri',
          'Banjar Jawa',
          'Banjar Tegal',
          'Beratan',
          'Kaliuntu',
          'Kampung Anyar',
          'Kampung Baru',
          'Kampung Bugis',
          'Kampung Kajanan',
          'Penarukan',
        ],
        'Seririt': ['Seririt', 'Banjar', 'Kalisada'],
        'Sukasada': ['Sukasada', 'Gitgit', 'Pancasari', 'Ambengan'],
      },
      'Kab. Tabanan': {
        'Tabanan': ['Tabanan', 'Dauh Peken', 'Delod Peken', 'Dajan Peken'],
        'Kediri': ['Kediri', 'Beraban (Tanah Lot)', 'Nyanyi'],
        'Baturiti': ['Baturiti', 'Bedugul', 'Candikuning'],
      },
      'Kab. Karangasem': {
        'Karangasem': ['Amlapura', 'Padangbai', 'Candi Dasa', 'Subagan'],
        'Manggis': ['Manggis', 'Antiga', 'Buitan'],
      },
      'Kab. Klungkung': {
        'Klungkung': ['Semarapura', 'Semarapura Kelod', 'Gelgel'],
        'Nusa Penida': ['Nusa Penida', 'Lembongan', 'Jungutbatu'],
      },
      'Kab. Bangli': {
        'Bangli': ['Bangli', 'Kintamani', 'Batur'],
      },
      'Kab. Jembrana': {
        'Negara': ['Negara', 'Gilimanuk', 'Lelateng'],
      },
    },
    'Lainnya (Luar NTB & Bali)': {
      'DKI Jakarta / Jawa / Lainnya': {
        'Kecamatan Umum': [
          'Pilih & Ketik Alamat Spesifik...',
        ],
      },
    },
  };

  static List<String> getProvinces() {
    return _wilayahMap.keys.toList();
  }

  static List<String> getRegencies(String province) {
    final kabMap = _wilayahMap[province];
    if (kabMap == null) return [];
    return kabMap.keys.toList();
  }

  static List<String> getDistricts(String province, String regency) {
    final kecMap = _wilayahMap[province]?[regency];
    if (kecMap == null) return [];
    return kecMap.keys.toList();
  }

  static List<String> getVillages(String province, String regency, String district) {
    final desaList = _wilayahMap[province]?[regency]?[district];
    if (desaList == null) return [];
    return desaList;
  }
}
